# Generated by Django 4.1.13 on 2024-01-15 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchdata',
            old_name='city_key',
            new_name='locationkey',
        ),
        migrations.AlterField(
            model_name='searchdata',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 15, 12, 41, 8, 98032)),
        ),
    ]
